
services:

  # Spring boot application Service
  blog-app:
    image: blog-app:1.5
    working_dir: /app
#    volumes:
#      - C:\Users\MaxwellAdomako\IdeaProjects\learnings\blog\target\blog-0.0.1-SNAPSHOT.jar:/app/blog-0.0.1-SNAPSHOT.jar
    ports:
      - 2020:2020
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/blogs
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres  // removed because app talks to the pg service
    env_file:
      - .env
    depends_on:
      - postgres
    restart: on-failure:1

  # Database Service
  postgres:
    container_name: blog_app_db
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      PG_DATA: ${PG_DATA}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ${SOURCE_VOLUME}
    ports:
      - ${DB_PORT}
    networks:
      - ${NETWORK}
    restart: unless-stopped

networks:
  blog-app-network:
    driver: bridge

volumes:
  postgres:
    driver: local

